[phases.setup]
runtime = "python:3.12"  # Ensure your Python version matches your app requirements
apt_pkgs = [
    "libmariadb-dev",
    "gcc",
    "pkg-config"  # Required for locating MySQL/MariaDB
]

